### ISSUE TITLE
issue with new version of file picker

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter-form-builder-ecosystem/form_builder_file_picker#11]
form_builder_file_picker >=1.1.0 depends on flutter_form_builder ^5.0.0 and "PROJECT" depends on flutter_form_builder ^6.0.0-nullsafety.1, form_builder_file_picker >=1.1.0 is forbidden

**Comment by ozyildirim** [comment]
any update?

**Comment by jrojas25** [comment]
Same issue, and is a mess to resolve by downgrading flutter_form_builder when you have other dependencies like firebase and http.

**Comment by deandreamatias** [comment]
Because this is an old version error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
