### ISSUE TITLE
File picker requires permission handler 9.2.0 while permission handler 10.0.0 is out now. Please update.

### ISSUE THREAD

**Issue by MonkeyDrone** [flutter-form-builder-ecosystem/form_builder_file_picker#30]
Because form_builder_file_picker 2.1.0 depends on permission_handler ^9.2.0 and no versions of form_builder_file_picker match >2.1.0 <3.0.0, form_builder_file_picker ^2.1.0 requires permission_handler ^9.2.0.

**Comment by deandreamatias** [comment]
Try use the last version of form_builder_file_picker that use a permission_handler 10.0.0
