### ISSUE TITLE
Build problem on ios platform (pipeline)

### ISSUE THREAD

**Issue by sawirricardo** [flutter-form-builder-ecosystem/form_builder_file_picker#50]
Hi, need to update the dependencies, especially FilePicker 5.2.2 to catch up with flutter's official plugins like package_info_plus and device_info_plugin

Edit: Need solve the build problem on ios to release new version

**Comment by deandreamatias** [comment]
Hi @sawirricardo.
I will update when posible
Thanks

**Comment by deandreamatias** [comment]
Currently I have a [build problem on ios](https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker/actions/runs/3509643602/jobs/5878883950). If you can test on Mac machine and solve it, I can release a new version.
Thanks!

**Comment by sawirricardo** [comment]
i'll take a look

**Comment by sawirricardo** [comment]
@deandreamatias , I took a look, and it seems the issue can be as simple as update the deployment target to `'13.0'`, but it will not support 12 and below version. Any advice?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/37329575/202946332-9b75e5de-4755-4316-b4d5-9cc7023f7fb0.png">

**Comment by sawirricardo** [comment]
Another reference issues I see is this https://github.com/flutter/flutter/issues/100142

however not quite sure which way we should take...

**Comment by sawirricardo** [comment]
Similar issues is this https://github.com/pichillilorenzo/flutter_inappwebview/issues/1216#issuecomment-1246339851

**Comment by deandreamatias** [comment]
To investigate the problem, can be useful this references:
- https://stackoverflow.com/questions/41904724/using-available-with-stored-properties/73699790#73699790
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/1238/files
- https://github.com/hypha-dao/hashed-wallet/pull/140

**Comment by deandreamatias** [comment]
Solved!
