### ISSUE TITLE
form_builder_file_picker ^2.3.0 is incompatible with package_info_plus >=3.0.0

### ISSUE THREAD

**Issue by darkwood-studios** [flutter-form-builder-ecosystem/form_builder_file_picker#54]
flutter pub get failed

I use 
form_builder_file_picker: ^2.3.0
package_info_plus: ^3.0.2

>>>
Because no versions of form_builder_file_picker match >2.3.0 <3.0.0 and form_builder_file_picker 2.3.0 depends on file_picker ^4.6.1, form_builder_file_picker ^2.3.0 requires file_picker ^4.6.1.
And because no versions of file_picker match >4.6.1 <5.0.0, form_builder_file_picker ^2.3.0 requires file_picker 4.6.1.
And because file_picker 4.6.1 depends on ffi ^1.1.2 and package_info_plus >=3.0.0 depends on ffi ^2.0.1, form_builder_file_picker ^2.3.0 is incompatible with package_info_plus >=3.0.0.
So, because teleson_app_flutter depends on both package_info_plus ^3.0.2 and form_builder_file_picker ^2.3.0, version solving failed.
pub get failed (1; So, because teleson_app_flutter depends on both package_info_plus ^3.0.2 and form_builder_file_picker ^2.3.0, version solving failed.)
<<<

**Comment by deandreamatias** [comment]
Try use override_dependencies to fix a version for conflicts dependencies

**Comment by deandreamatias** [comment]
Solved on last version!
