### ISSUE TITLE
unable to install the package...

### ISSUE THREAD

**Issue by discnx** [flutter-form-builder-ecosystem/form_builder_file_picker#9]
Because form_builder_file_picker >=0.2.0 depends on flutter_form_builder ^3.10.0 and app depends on flutter_form_builder ^4.0.2, form_builder_file_picker >=0.2.0 is forbidden.

So, because app depends on form_builder_file_picker ^0.3.0, version solving failed.
pub get failed (1; So, because app depends on form_builder_file_picker ^0.3.0, version solving failed.)
exit code 1

**Comment by deandreamatias** [comment]
Because this is an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
